"""Python conformance runner over the shared NDJSON vectors.

Loads `conformance/{codec,signing,nonce,errors}.ndjson` (generated by the Rust
core) and asserts the Python binding reproduces every `expect`. A divergence
here is a cross-language codec/signing/nonce/error-classification bug — a
release blocker.

Vectors are generated by `crates/spec` (`gen-vectors`). Byte fields in the
`input` are arrays of u8 (pythonize routes them straight into the wire
newtypes), so no hex/byte massaging is needed for codec inputs.
"""

from __future__ import annotations

import json
from pathlib import Path

import proof_trading_sdk as pts
from proof_trading_sdk import _native, actions
from proof_trading_sdk.nonce import NonceAllocator

_DIR = Path(__file__).resolve().parents[2] / "conformance"


def _cases(name: str):
    path = _DIR / name
    with path.open() as f:
        for n, line in enumerate(f, start=1):
            line = line.strip()
            if line:
                yield n, json.loads(line)


class TestCodecVectors:
    def test_payload_matches_core(self):
        seen = 0
        for n, c in _cases("codec.ndjson"):
            payload = _native.encode_action(c["action_type"], c["input"])
            assert payload.hex() == c["expect"]["payload_hex"], (
                f"codec.ndjson:{n} case {c['case']!r}"
            )
            seen += 1
        assert seen > 0, "no codec vectors loaded"

    def test_uncapped_create_market_vectors_share_canonical_v2_bytes(self):
        vectors = {
            c["case"]: c
            for _, c in _cases("codec.ndjson")
            if c["case"].startswith("create_market/")
        }
        omitted = vectors["create_market/full"]
        explicit_zero = vectors[
            "create_market/max_open_interest_zero_explicit"
        ]
        expected = omitted["expect"]["payload_hex"]
        assert explicit_zero["expect"]["payload_hex"] == expected
        assert expected.startswith("9c")  # MessagePack fixarray(12)

        for case in (omitted, explicit_zero):
            payload = _native.encode_action(case["action_type"], case["input"])
            assert payload.hex() == expected
            decoded = _native.decode_action(case["action_type"], payload)
            assert decoded["max_open_interest"] == 0


class TestResolveActionVectors:
    """DEC-149: byte 0x0f is the legacy impact-family resolve
    (``ResolveImpactMarket``, reachable only through ``RawAction``); the
    standalone-event resolve is ``ResolveEvent`` (0x27) with a dedicated
    builder. Both bytes come from the core, and both builders are pinned to
    the authoritative codec vectors — not to hand-copied hex."""

    def test_resolve_action_bytes_come_from_the_core(self):
        table = {e["name"]: e["code"] for e in _native.get_action_types()}
        assert table["ResolveImpactMarket"] == 0x0F
        assert table["ResolveEvent"] == 0x27
        assert actions.ActionType["ResolveImpactMarket"] == 0x0F
        assert actions.ActionType["ResolveEvent"] == 0x27

    def test_resolve_event_builder_matches_both_0x27_vectors(self):
        seen = 0
        for n, c in _cases("codec.ndjson"):
            if not c["case"].startswith("resolve_event/"):
                continue
            assert c["action_type"] == 0x27, f"codec.ndjson:{n}"
            act = actions.ResolveEvent(
                event_id=c["input"]["event_id"],
                outcome=c["input"]["outcome"],
                signer=bytes(c["input"]["signer"]),
            )
            action_type, payload = actions.encode_action(act)
            assert action_type == 0x27
            assert payload.hex() == c["expect"]["payload_hex"], (
                f"codec.ndjson:{n} case {c['case']!r}"
            )
            seen += 1
        assert seen == 2, "expected the resolve_event/yes and /no vectors"

    def test_resolve_impact_market_raw_action_matches_all_three_0x0f_vectors(self):
        seen = 0
        for n, c in _cases("codec.ndjson"):
            if not c["case"].startswith("resolve_impact_market/"):
                continue
            assert c["action_type"] == 0x0F, f"codec.ndjson:{n}"
            act = actions.RawAction(
                actions.ActionType.ResolveImpactMarket,
                {
                    "impact_market_id": c["input"]["impact_market_id"],
                    "outcome": c["input"]["outcome"],
                    "signer": bytes(c["input"]["signer"]),
                },
            )
            action_type, payload = actions.encode_action(act)
            assert action_type == 0x0F
            assert payload.hex() == c["expect"]["payload_hex"], (
                f"codec.ndjson:{n} case {c['case']!r}"
            )
            # The frozen bytes decode back to the same fields (Yes / No / Void).
            decoded = actions.decode_action(action_type, payload)
            assert decoded["impact_market_id"] == c["input"]["impact_market_id"]
            assert decoded["outcome"] == c["input"]["outcome"]
            assert bytes(decoded["signer"]) == bytes(c["input"]["signer"])
            seen += 1
        assert seen == 3, "expected the yes / no / void vectors"


class TestSigningVectors:
    def test_sign_and_owner_match_core(self):
        seen = 0
        for n, c in _cases("signing.ndjson"):
            if c["kind"] == "sign":
                env = pts.sign_and_encode(
                    bytes(c["chain_id"]),
                    c["action_type"],
                    bytes.fromhex(c["payload_hex"]),
                    c["seq"],
                    bytes(c["secret_key"]),
                )
                assert env.hex() == c["expect_envelope_hex"], (
                    f"signing.ndjson:{n} case {c['case']!r}"
                )
            elif c["kind"] == "owner":
                owner = pts.pubkey_to_owner(bytes(c["pubkey"]))
                assert owner.hex() == c["expect_owner_hex"], (
                    f"signing.ndjson:{n} case {c['case']!r}"
                )
            else:
                raise AssertionError(f"unknown signing kind: {c['kind']!r}")
            seen += 1
        assert seen > 0, "no signing vectors loaded"


class TestErrorVectors:
    def test_code_to_name_matches_core(self):
        # Bare code (log null) → numeric manifest name; code + log → the
        # log-aware decoder. Both derive from the Rust core.
        table = {e["code"]: e["name"] for e in _native.get_error_code_table()}
        seen = 0
        for n, c in _cases("errors.ndjson"):
            expected = c["expect"]["name"]
            if c["log"] is None:
                got = table.get(c["code"])
            else:
                got = pts.get_error_name(c["code"], c["log"])
            assert got == expected, f"errors.ndjson:{n} case {c['case']!r}"
            seen += 1
        assert seen > 0, "no error vectors loaded"


class TestNonceVectors:
    def test_step_sequence_matches_core(self):
        seen = 0
        for n, c in _cases("nonce.ndjson"):
            last = c["last"]
            out = []
            for now in c["now_ms"]:
                last = NonceAllocator.step(last, now)
                out.append(last)
            assert out == c["expect"], f"nonce.ndjson:{n} case {c['case']!r}"
            seen += 1
        assert seen > 0, "no nonce vectors loaded"
