"""Python conformance runner over the shared NDJSON vectors.

Loads `conformance/{codec,signing,nonce}.ndjson` (generated by the Rust core)
and asserts the Python binding reproduces every `expect`. A divergence here
is a cross-language codec/signing/nonce bug — a release blocker.

Vectors are generated by `crates/spec` (`gen-vectors`). Byte fields in the
`input` are arrays of u8 (pythonize routes them straight into the wire
newtypes), so no hex/byte massaging is needed for codec inputs.
"""

from __future__ import annotations

import json
from pathlib import Path

import proof_trading_sdk as pts
from proof_trading_sdk import _native
from proof_trading_sdk.nonce import NonceAllocator

_DIR = Path(__file__).resolve().parents[2] / "conformance"


def _cases(name: str):
    path = _DIR / name
    with path.open() as f:
        for n, line in enumerate(f, start=1):
            line = line.strip()
            if line:
                yield n, json.loads(line)


class TestCodecVectors:
    def test_payload_matches_core(self):
        seen = 0
        for n, c in _cases("codec.ndjson"):
            payload = _native.encode_action(c["action_type"], c["input"])
            assert payload.hex() == c["expect"]["payload_hex"], (
                f"codec.ndjson:{n} case {c['case']!r}"
            )
            seen += 1
        assert seen > 0, "no codec vectors loaded"

    def test_uncapped_create_market_vectors_share_canonical_v2_bytes(self):
        vectors = {
            c["case"]: c
            for _, c in _cases("codec.ndjson")
            if c["case"].startswith("create_market/")
        }
        omitted = vectors["create_market/full"]
        explicit_zero = vectors[
            "create_market/max_open_interest_zero_explicit"
        ]
        expected = omitted["expect"]["payload_hex"]
        assert explicit_zero["expect"]["payload_hex"] == expected
        assert expected.startswith("9c")  # MessagePack fixarray(12)

        for case in (omitted, explicit_zero):
            payload = _native.encode_action(case["action_type"], case["input"])
            assert payload.hex() == expected
            decoded = _native.decode_action(case["action_type"], payload)
            assert decoded["max_open_interest"] == 0


class TestSigningVectors:
    def test_sign_and_owner_match_core(self):
        seen = 0
        for n, c in _cases("signing.ndjson"):
            if c["kind"] == "sign":
                env = pts.sign_and_encode(
                    bytes(c["chain_id"]),
                    c["action_type"],
                    bytes.fromhex(c["payload_hex"]),
                    c["seq"],
                    bytes(c["secret_key"]),
                )
                assert env.hex() == c["expect_envelope_hex"], (
                    f"signing.ndjson:{n} case {c['case']!r}"
                )
            elif c["kind"] == "owner":
                owner = pts.pubkey_to_owner(bytes(c["pubkey"]))
                assert owner.hex() == c["expect_owner_hex"], (
                    f"signing.ndjson:{n} case {c['case']!r}"
                )
            else:
                raise AssertionError(f"unknown signing kind: {c['kind']!r}")
            seen += 1
        assert seen > 0, "no signing vectors loaded"


class TestNonceVectors:
    def test_step_sequence_matches_core(self):
        seen = 0
        for n, c in _cases("nonce.ndjson"):
            last = c["last"]
            out = []
            for now in c["now_ms"]:
                last = NonceAllocator.step(last, now)
                out.append(last)
            assert out == c["expect"], f"nonce.ndjson:{n} case {c['case']!r}"
            seen += 1
        assert seen > 0, "no nonce vectors loaded"
