"""Python conformance runner over the shared NDJSON vectors.

Loads `conformance/{codec,signing,nonce,errors}.ndjson` (generated by the Rust
core) and asserts the Python binding reproduces every `expect`. A divergence
here is a cross-language codec/signing/nonce/error-classification bug — a
release blocker.

Vectors are generated by `crates/spec` (`gen-vectors`). Byte fields in the
`input` are arrays of u8 (pythonize routes them straight into the wire
newtypes), so no hex/byte massaging is needed for codec inputs.
"""

from __future__ import annotations

import json
from pathlib import Path

import proof_trading_sdk as pts
from proof_trading_sdk import _native
from proof_trading_sdk.nonce import NonceAllocator

_DIR = Path(__file__).resolve().parents[2] / "conformance"


def _cases(name: str):
    path = _DIR / name
    with path.open() as f:
        for n, line in enumerate(f, start=1):
            line = line.strip()
            if line:
                yield n, json.loads(line)


class TestCodecVectors:
    def test_payload_matches_core(self):
        seen = 0
        for n, c in _cases("codec.ndjson"):
            payload = _native.encode_action(c["action_type"], c["input"])
            assert payload.hex() == c["expect"]["payload_hex"], (
                f"codec.ndjson:{n} case {c['case']!r}"
            )
            seen += 1
        assert seen > 0, "no codec vectors loaded"

    def test_uncapped_create_market_vectors_share_canonical_v2_bytes(self):
        vectors = {
            c["case"]: c
            for _, c in _cases("codec.ndjson")
            if c["case"].startswith("create_market/")
        }
        omitted = vectors["create_market/full"]
        explicit_zero = vectors[
            "create_market/max_open_interest_zero_explicit"
        ]
        expected = omitted["expect"]["payload_hex"]
        assert explicit_zero["expect"]["payload_hex"] == expected
        assert expected.startswith("9c")  # MessagePack fixarray(12)

        for case in (omitted, explicit_zero):
            payload = _native.encode_action(case["action_type"], case["input"])
            assert payload.hex() == expected
            decoded = _native.decode_action(case["action_type"], payload)
            assert decoded["max_open_interest"] == 0


class TestSigningVectors:
    def test_sign_and_owner_match_core(self):
        seen = 0
        for n, c in _cases("signing.ndjson"):
            if c["kind"] == "sign":
                env = pts.sign_and_encode(
                    bytes(c["chain_id"]),
                    c["action_type"],
                    bytes.fromhex(c["payload_hex"]),
                    c["seq"],
                    bytes(c["secret_key"]),
                )
                assert env.hex() == c["expect_envelope_hex"], (
                    f"signing.ndjson:{n} case {c['case']!r}"
                )
            elif c["kind"] == "owner":
                owner = pts.pubkey_to_owner(bytes(c["pubkey"]))
                assert owner.hex() == c["expect_owner_hex"], (
                    f"signing.ndjson:{n} case {c['case']!r}"
                )
            else:
                raise AssertionError(f"unknown signing kind: {c['kind']!r}")
            seen += 1
        assert seen > 0, "no signing vectors loaded"


class TestErrorVectors:
    def test_code_to_name_matches_core(self):
        # Bare code (log null) → numeric manifest name; code + log → the
        # log-aware decoder. Both derive from the Rust core.
        table = {e["code"]: e["name"] for e in _native.get_error_code_table()}
        seen = 0
        for n, c in _cases("errors.ndjson"):
            expected = c["expect"]["name"]
            if c["log"] is None:
                got = table.get(c["code"])
            else:
                got = pts.get_error_name(c["code"], c["log"])
            assert got == expected, f"errors.ndjson:{n} case {c['case']!r}"
            seen += 1
        assert seen > 0, "no error vectors loaded"


class TestNonceVectors:
    def test_step_sequence_matches_core(self):
        seen = 0
        for n, c in _cases("nonce.ndjson"):
            last = c["last"]
            out = []
            for now in c["now_ms"]:
                last = NonceAllocator.step(last, now)
                out.append(last)
            assert out == c["expect"], f"nonce.ndjson:{n} case {c['case']!r}"
            seen += 1
        assert seen > 0, "no nonce vectors loaded"


def _limb_from(value):
    return None if value is None else pts.TriggerLimb(**value)


class TestBinaryVectors:
    def test_no_orders_and_views_match_core(self):
        seen = 0
        for n, c in _cases("binary.ndjson"):
            where = f"binary.ndjson:{n} case {c['case']!r}"
            if c["kind"] == "no_order":
                i = c["input"]
                args = dict(
                    side=i["side"],
                    market=i["market"],
                    owner=bytes(i["owner"]),
                    price=i["price"],
                    quantity=i["quantity"],
                    client_order_id=i["client_order_id"],
                    post_only=i["post_only"],
                    reduce_only=i["reduce_only"],
                    time_in_force=i["time_in_force"],
                )
                expect = c["expect"]
                if "error" in expect:
                    try:
                        pts.no_order(
                            **args,
                            stop_loss=_limb_from(i["stop_loss"]),
                            take_profit=_limb_from(i["take_profit"]),
                        )
                    except pts.BinaryPriceError as error:
                        assert error.reason == expect["error"]["name"], where
                    except ValueError:
                        # A limb at 0 is refused by TriggerLimb itself, before
                        # the mirror is reached.
                        assert expect["error"]["name"] == "TriggerPriceOutOfRange", where
                    else:
                        raise AssertionError(f"{where}: expected a refusal")
                else:
                    order = pts.no_order(
                        **args,
                        stop_loss=_limb_from(i["stop_loss"]),
                        take_profit=_limb_from(i["take_profit"]),
                    )
                    fields = order.fields()
                    fields["owner"] = list(fields["owner"])
                    assert fields == expect["yes_order"]["fields"], where
                    payload = _native.encode_action(order.action_type, order.fields())
                    assert payload.hex() == expect["yes_order"]["payload_hex"], where
            else:
                expect = c["expect"]
                if "error" in expect:
                    try:
                        pts.binary_position_view(c["side"], c["entry_price"], c["size"])
                    except pts.BinaryPriceError as error:
                        assert error.reason == expect["error"]["name"], where
                    else:
                        raise AssertionError(f"{where}: expected a refusal")
                else:
                    view = pts.binary_position_view(c["side"], c["entry_price"], c["size"])
                    assert (view.outcome, view.entry_price, view.size) == (
                        expect["view"]["outcome"],
                        expect["view"]["entry_price"],
                        expect["view"]["size"],
                    ), where
            seen += 1
        assert seen > 0
