// Types
export {
  type Address,
  Side,
  TimeInForce,
  ActionType,
  type ActionTypeValue,
  type Action,
  type TraderAction,
  type OperatorAction,
  type PlaceOrder,
  type CancelOrder,
  type CancelClientOrder,
  type CancelAllOrders,
  type CancelReplaceOrder,
  type AmendOrder,
  type AtomicBasketLeg,
  type AtomicBasketOrder,
  type ClosePosition,
  type OracleUpdate,
  type OracleUpdateComposite,
  type MarketOrder,
  type Deposit,
  type Withdraw,
  type CreateMarket,
  type WithdrawRequest,
  type ConfirmDeposit,
  type ConfirmWithdrawal,
  type FailWithdrawal,
  type ApproveAgent,
  type RevokeAgent,
  type CreateImpactMarket,
  type EventOracleSource,
  type PriceComparison,
  type ResolveEvent,
  type UpdateMarketFees,
  type SetUserMarketLeverage,
  type ImpactMarketInfo,
  type ImpactMarketStatus,
  Branch,
  Outcome,
  type TxResult,
  type TxOutcome,
  type TxEvent,
  type ExchangeEvent,
  type OrderPlacedEvent,
  type OrderCancelledEvent,
  type TradeExecutedEvent,
  type PositionUpdatedEvent,
  type PositionClosedEvent,
  type PriceUpdatedEvent,
  type FundingAppliedEvent,
  type FundingSettledEvent,
  type AccountLiquidatedEvent,
  type MarketCreatedEvent,
  type AdlQueueEntry,
  type Ticker,
  type Orderbook,
  type OrderbookLevel,
  type OpenOrder,
  type AccountInfo,
  type PositionInfo,
  type MarketConfig,
  type MarkSourceMode,
  type BindingScenarioEntry,
  type HistoryCashFlow,
  type HistoryResolution,
  type HistoryPositionSnapshot,
  type WithdrawalStatus,
  type WithdrawalRecord,
  type MarketKind,
  type FeeTier,
  type AgentApprovedEvent,
  type AgentRevokedEvent,
  type FeesCollectedEvent,
} from "./types.js";

// Codec
export {
  ENVELOPE_VERSION,
  encodeSignedTx,
  signAndEncode,
  signEnvelopeFromPayload,
  encodePayloadBytes,
  decodeTx,
  decodeSigningMessage,
  type DecodedSigningMessage,
  peekActionType,
} from "./codec.js";
// WASM codec/signing core init. `await ready()` once before any codec/signing
// call (the `ExchangeClient` does this for you). See ADR 0001.
export { ready } from "./wasm-loader.js";
export { fetchChainId } from "./client.js";

// Error decoder
export {
  type ExecErrorInfo,
  ExecErrorCode,
  decodeExecError,
  execErrorName,
} from "./errors.js";

// Crypto
export {
  generateKeypair,
  getPublicKey,
  pubkeyToOwner,
  ownerToHex,
  hexToBytes,
  bytesToHex,
  signingMessage,
  sign,
  verify,
  chainIdFromString,
  UNBOUND_CHAIN_ID,
  DOMAIN_PREFIX,
} from "./crypto.js";

// Client
export {
  ExchangeClient,
  type ExchangeClientOptions,
  type WsStreamOptions,
} from "./client.js";
