// Types
export {
  type Address,
  Side,
  TimeInForce,
  ActionType,
  type ActionTypeValue,
  type Action,
  type TraderAction,
  type OperatorAction,
  type PlaceOrder,
  type CancelOrder,
  type CancelClientOrder,
  type CancelAllOrders,
  type CancelReplaceOrder,
  type AmendOrder,
  type AtomicBasketLeg,
  type AtomicBasketOrder,
  type ClosePosition,
  type OracleUpdate,
  type OracleUpdateComposite,
  type MarketOrder,
  type Deposit,
  type Withdraw,
  type CreateMarket,
  type WithdrawRequest,
  type ConfirmDeposit,
  type ConfirmWithdrawal,
  type FailWithdrawal,
  type ConfirmWithdrawalReceipt,
  type FailWithdrawalReceipt,
  type AuthorizeWithdrawal,
  type TriggerLimb,
  type SetPositionTriggers,
  type CancelPositionTriggers,
  type SetTriggerMarketConfig,
  type BridgeWithdrawalReceipt,
  type OperatorReceiptProof,
  type ApproveAgent,
  type RevokeAgent,
  type CreateImpactMarket,
  type EventOracleSource,
  type PriceComparison,
  type ResolveEvent,
  type UpdateMarketFees,
  type SetUserMarketLeverage,
  type GovernanceAction,
  type AdminAction,
  type AdminBatchItem,
  type EmergencyAction,
  type UpdateAdminSignerRegistry,
  type ProposeAdminAction,
  type ApproveAdminAction,
  type RejectAdminAction,
  type EmergencyAdminAction,
  type AdminSignerRegistry,
  type ExpiryReason,
  type ProposalStatus,
  type ProposalDisplayInfo,
  type ProposalPage,
  type ImpactMarketInfo,
  type ImpactMarketStatus,
  Branch,
  Outcome,
  type TxResult,
  type TxOutcome,
  type TxEvent,
  type ExchangeEvent,
  type OrderPlacedEvent,
  type OrderCancelledEvent,
  type TradeExecutedEvent,
  type PositionUpdatedEvent,
  type PositionClosedEvent,
  type PriceUpdatedEvent,
  type FundingAppliedEvent,
  type FundingSettledEvent,
  type AccountLiquidatedEvent,
  type MarketCreatedEvent,
  type AdlQueueEntry,
  type Ticker,
  type Orderbook,
  type OrderbookLevel,
  type OpenOrder,
  type TriggerKind,
  type TriggerLimbState,
  type TriggerOutcomeReason,
  type TriggerEvaluation,
  type StoredTriggerLimb,
  type TriggerMarketConfig,
  type PendingTriggerMarketConfig,
  type TriggerMarketConfigState,
  type TriggerMarketConfigInfo,
  type TriggerEffectiveAvailability,
  type PositionTriggerBracket,
  type PositionTriggerInfo,
  type TriggerStatus,
  type TriggerHistoryTime,
  type PositionTriggerHistoryFilters,
  type TriggerMarketHistoryFilters,
  type PositionTriggerHistoryEventType,
  type TriggerMarketHistoryEventType,
  type TriggerHistoryEventType,
  type TriggerHistoryPayloadBase,
  type OwnerTriggerHistoryPayloadBase,
  type PositionTriggersSetHistoryPayload,
  type PositionTriggersCancelledHistoryPayload,
  type PositionTriggersInvalidatedHistoryPayload,
  type PositionTriggerActivatedHistoryPayload,
  type PositionTriggerExecutedHistoryPayload,
  type PositionTriggerDeferredHistoryPayload,
  type TriggerMarketDeferredHistoryPayload,
  type TriggerMarketResumedHistoryPayload,
  type TriggerHistoryEvent,
  type PositionTriggerHistoryEvent,
  type TriggerMarketHistoryEvent,
  type PositionTriggerHistoryPage,
  type TriggerMarketHistoryPage,
  type AccountInfo,
  type PositionInfo,
  type MarketConfig,
  type MarkSourceMode,
  type BindingScenarioEntry,
  type HistoryCashFlow,
  type HistoryFill,
  type HistoryFillsPage,
  type HistoryResolution,
  type HistoryPositionSnapshot,
  type WithdrawalStatus,
  type WithdrawalRecord,
  type MarketKind,
  type FeeTier,
  type AgentApprovedEvent,
  type AgentRevokedEvent,
  type FeesCollectedEvent,
} from "./types.js";

export {
  MAX_TRIGGER_SLIPPAGE_BPS,
  validateSetPositionTriggers,
  validateCancelPositionTriggers,
  validateSetTriggerMarketConfig,
  decodePositionTriggerInfos,
  decodeTriggerMarketConfigInfos,
  decodeTriggerStatusJson,
} from "./triggers.js";

export {
  decodePositionTriggerHistoryPage,
  decodeTriggerMarketHistoryPage,
  positionTriggerHistorySearchParams,
  triggerMarketHistorySearchParams,
} from "./trigger-history.js";

// Codec
export {
  ENVELOPE_VERSION,
  encodeSignedTx,
  signAndEncode,
  signEnvelopeFromPayload,
  encodePayloadBytes,
  decodeTx,
  decodeSigningMessage,
  type DecodedSigningMessage,
  peekActionType,
  adminProposalContentHash,
  type AdminProposalContext,
} from "./codec.js";
// WASM codec/signing core init. `await ready()` once before any codec/signing
// call (the `ExchangeClient` does this for you). See ADR 0001.
export { ready } from "./wasm-loader.js";

// Governance read-model decoders. Exported so a caller holding raw proxy
// bytes (an offline signer tool reconstructing an approval, say) can decode
// them with the same pinned implementation the client uses, rather than
// re-deriving the engine's positional layout by hand.
export {
  decodeAdminAction,
  decodeAdminSignerRegistry,
  decodeAdminSignerRegistryInfo,
  decodeProposalPage,
  decodeProposalDisplayInfo,
  decodeProposalStatus,
} from "./governance-query.js";
export { fetchChainId } from "./client.js";

// Error decoder
export {
  type ExecErrorInfo,
  ExecErrorCode,
  decodeExecError,
  execErrorName,
} from "./errors.js";

// Crypto
export {
  generateKeypair,
  getPublicKey,
  pubkeyToOwner,
  ownerToHex,
  hexToBytes,
  bytesToHex,
  signingMessage,
  sign,
  verify,
  chainIdFromString,
  UNBOUND_CHAIN_ID,
  DOMAIN_PREFIX,
} from "./crypto.js";

// Client
export {
  ExchangeClient,
  type ExchangeClientOptions,
  type WsStreamOptions,
} from "./client.js";
