use crate::types::*;
use serde::{de::DeserializeOwned, Deserialize, Deserializer, Serialize, Serializer};

/// Structured output of encoding an action payload for the wire.
struct EncodedAction {
    action_type: u8,
    payload: WireBlob,
}

/// Trait that pairs each action payload type with its wire discriminant
/// and provides msgpack encode/decode.
trait EncodePayload: Serialize + DeserializeOwned {
    const ACTION_TYPE: u8;

    fn encode_payload(&self) -> Result<WireBlob, ExecError> {
        let bytes = rmp_serde::to_vec(self).map_err(|e| ExecError::InternalError(e.to_string()))?;
        Ok(WireBlob(bytes))
    }

    fn encode_action(&self) -> Result<EncodedAction, ExecError> {
        self.encode_payload().map(|payload| EncodedAction {
            action_type: Self::ACTION_TYPE,
            payload,
        })
    }
}

macro_rules! impl_action_encoding {
    ($($ty:ident => $code:expr),+ $(,)?) => {
        /// Top-level transaction action enum. MessagePack tag selects the
        /// variant. Each variant wraps the corresponding payload struct.
        ///
        /// Every variant here has an `ACTION_TYPE` constant (generated by the
        /// same macro) and appears in `get_action_types()` — the list is the
        /// single source of truth for encode, decode, and the name↔code map.
        #[derive(Clone, Debug, Serialize, Deserialize, derive_more::From)]
        pub enum Action {
            $(
                #[doc = concat!("See [`", stringify!($ty), "`].")]
                $ty($ty),
            )+
        }

        $(impl EncodePayload for $ty {
            const ACTION_TYPE: u8 = $code;
        })+

        impl Action {
            fn encode_action(&self) -> Result<EncodedAction, ExecError> {
                match self {
                    $(Self::$ty(cmd) => cmd.encode_action()),+,
                }
            }
        }

        fn decode_action(action_type: u8, payload: &[u8]) -> Result<Action, ExecError> {
            let de = |e: rmp_serde::decode::Error| ExecError::DecodeError(e.to_string());
            match action_type {
                $($code => rmp_serde::from_slice::<$ty>(payload).map_err(de).map(Action::from)),+,
                other => Err(ExecError::DecodeError(format!(
                    "unknown action_type: {other:#x}"
                ))),
            }
        }

        /// Deserialize a structured action payload (from any self-describing
        /// source — `pythonize`, `serde_wasm_bindgen`, JSON …) into the typed
        /// payload struct for `action_type`, then encode it to the exact
        /// MessagePack wire bytes via the same `rmp-serde` path the engine
        /// uses. This is the single bridge entry point that lets native
        /// bindings hand the core *field values* and get authoritative
        /// payload bytes back — no per-language codec, no field-order drift.
        ///
        /// Generated by the same macro as encode/decode so a new action is
        /// covered automatically.
        pub fn encode_payload_dyn<'de, D: serde::Deserializer<'de>>(
            action_type: u8,
            de: D,
        ) -> Result<Vec<u8>, ExecError> {
            match action_type {
                $($code => {
                    let value = <$ty as serde::Deserialize>::deserialize(de)
                        .map_err(|e| ExecError::DecodeError(e.to_string()))?;
                    value.encode_payload().map(|b| b.0)
                })+,
                other => Err(ExecError::DecodeError(format!(
                    "unknown action_type: {other:#x}"
                ))),
            }
        }

        /// Decode raw MessagePack payload bytes for `action_type` into the
        /// typed payload struct, then re-serialize into the provided
        /// `Serializer` (e.g. `pythonize`'s `Pythonizer`). The inverse of
        /// [`encode_payload_dyn`]; lets a binding hand back a native object
        /// (Python dict, JS object) without reimplementing field order.
        pub fn decode_payload_dyn<S: serde::Serializer>(
            action_type: u8,
            payload: &[u8],
            ser: S,
        ) -> Result<S::Ok, ExecError> {
            let de = |e: rmp_serde::decode::Error| ExecError::DecodeError(e.to_string());
            match action_type {
                $($code => {
                    let value = rmp_serde::from_slice::<$ty>(payload).map_err(de)?;
                    value
                        .serialize(ser)
                        .map_err(|e| ExecError::InternalError(e.to_string()))
                })+,
                other => Err(ExecError::DecodeError(format!(
                    "unknown action_type: {other:#x}"
                ))),
            }
        }

        /// Return all action-type name → code mappings. Generated by the same
        /// macro that defines encoding — adding a new action here automatically
        /// adds it to the manifest.
        pub fn get_action_types() -> Vec<(&'static str, u8)> {
            fn entry<A: EncodePayload>(name: &'static str) -> (&'static str, u8) {
                (name, A::ACTION_TYPE)
            }
            vec![$(
                entry::<$ty>(stringify!($ty)),
            )+]
        }
    }
}

impl_action_encoding! {
    PlaceOrder => 0x01,
    CancelOrder => 0x02,
    CancelClientOrder => 0x18,
    CancelAllOrders => 0x19,
    CancelReplaceOrder => 0x1A,
    OracleUpdate => 0x03,
    OracleUpdateComposite => 0x14,
    MarketOrder => 0x04,
    Deposit => 0x05,
    Withdraw => 0x06,
    CreateMarket => 0x07,
    WithdrawRequest => 0x08,
    ConfirmDeposit => 0x09,
    ConfirmWithdrawal => 0x0A,
    FailWithdrawal => 0x0B,
    ApproveAgent => 0x0C,
    RevokeAgent => 0x0D,
    CreateImpactMarket => 0x0E,
    ResolveEvent => 0x0F,
    UpdateMarketFees => 0x10,
    SetUserMarketLeverage => 0x16,
    ClosePosition => 0x17,
    AmendOrder => 0x1B,
    AtomicBasketOrder => 0x1C,
}

/// Byte buffer that always serializes as msgpack `bin` (0xc4/c5/c6),
/// never as msgpack `array` (0xdc/0xdd). Used in `WireTxEnvelope` fields
/// that must match the Go CheckTx parser's wire format.
#[derive(Clone, Debug)]
struct WireBlob(Vec<u8>);

impl Serialize for WireBlob {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        serde_bytes::Bytes::new(&self.0).serialize(s)
    }
}

impl<'de> Deserialize<'de> for WireBlob {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        serde_bytes::ByteBuf::deserialize(d).map(|b| WireBlob(b.into_vec()))
    }
}

#[cfg(test)]
impl WireBlob {
    fn from_test_payload(bytes: Vec<u8>) -> Self {
        WireBlob(bytes)
    }
}

impl std::ops::Deref for WireBlob {
    type Target = Vec<u8>;

    fn deref(&self) -> &Vec<u8> {
        &self.0
    }
}

/// Envelope version emitted by this build.
pub const ENVELOPE_VERSION: u8 = 2;

/// Wire envelope versions this build accepts on decode. Single source of
/// truth — mirrored by `supportedEnvelopeVersions` in
/// `exchange-node/check_tx.go` and the SDK check in `sdk/src/codec.ts`.
/// Add a new version here when introducing one; drop an old one when it
/// is no longer permitted. Decoders MUST consult this slice instead of
/// hardcoding numeric comparisons.
pub const SUPPORTED_ENVELOPE_VERSIONS: &[u8] = &[ENVELOPE_VERSION];

/// Wire envelope: `[version=2, action_type, seq, payload_bytes, pubkey, signature]`.
///
/// Byte fields use [`WireBlob`] which enforces msgpack `bin` encoding at the
/// type level (not just an annotation). The Go CheckTx parser
/// (exchange-node/check_tx.go) and the SDK both expect this shape.
///
/// The envelope `version` byte stays `2` (exchange-core accepts only `[2]`).
/// This is independent of the signing **domain prefix**, which is
/// `"ProofExchange-v3"` (see `crypto.rs`) — bumped to v3 when chain_id
/// binding landed. The legacy unsigned (v1) envelope was removed pre-launch.
#[derive(Serialize, Deserialize)]
struct WireTxEnvelope {
    version: u8,
    action_type: u8,
    seq: u64,
    payload: WireBlob,
    #[serde(with = "serde_bytes")]
    pubkey: [u8; 32],
    #[serde(with = "serde_bytes")]
    signature: [u8; 64],
}

/// Authentication data extracted from the wire envelope.
#[derive(Debug)]
pub struct TxAuth {
    pub pubkey: [u8; 32],
    pub signature: [u8; 64],
    pub action_type: u8,
    pub payload: Vec<u8>,
}

/// Result of decoding a transaction.
#[derive(Debug)]
pub struct DecodedTx {
    pub action: Action,
    pub seq: u64,
    pub auth: TxAuth,
}

/// Decode raw tx bytes as a signed wire envelope:
/// fixarray(6) `[version=2, action_type, seq, payload, pubkey, signature]`.
pub fn decode_tx(bytes: &[u8]) -> Result<DecodedTx, ExecError> {
    if bytes.is_empty() {
        return Err(ExecError::DecodeError("empty tx".to_string()));
    }

    let envelope: WireTxEnvelope =
        rmp_serde::from_slice(bytes).map_err(|e| ExecError::DecodeError(e.to_string()))?;

    if !SUPPORTED_ENVELOPE_VERSIONS.contains(&envelope.version) {
        return Err(ExecError::DecodeError(format!(
            "unsupported envelope version: {} (supported: {:?})",
            envelope.version, SUPPORTED_ENVELOPE_VERSIONS
        )));
    }

    let action = decode_action(envelope.action_type, &envelope.payload)?;

    Ok(DecodedTx {
        action,
        seq: envelope.seq,
        auth: TxAuth {
            pubkey: envelope.pubkey,
            signature: envelope.signature,
            action_type: envelope.action_type,
            payload: envelope.payload.0,
        },
    })
}

/// Encode an action with a pre-computed pubkey + signature into a wire envelope.
/// Most callers should use [`sign_and_encode`] instead; this exists for paths
/// (api-gateway forward, FFI relays) that already hold raw signature bytes.
pub fn encode_signed_tx(
    action: &Action,
    seq: u64,
    pubkey: &[u8; 32],
    signature: &[u8; 64],
) -> Result<Vec<u8>, ExecError> {
    let EncodedAction {
        action_type,
        payload,
    } = action.encode_action()?;
    let envelope = WireTxEnvelope {
        version: ENVELOPE_VERSION,
        action_type,
        seq,
        payload,
        pubkey: *pubkey,
        signature: *signature,
    };
    rmp_serde::to_vec(&envelope).map_err(|e| ExecError::InternalError(e.to_string()))
}

/// Sign an action and encode it as a wire envelope, binding the
/// signature to a specific `chain_id`. The signing bytes carry a 32-byte
/// chain_id prefix per audit B4 — `chain_id` is established by
/// genesis / snapshot-load, not carried on the wire.
pub fn sign_and_encode_with_chain(
    chain_id: &[u8; 32],
    action: &Action,
    seq: u64,
    signing_key: &ed25519_dalek::SigningKey,
) -> Result<Vec<u8>, ExecError> {
    use ed25519_dalek::Signer;

    let EncodedAction {
        action_type,
        payload,
    } = action.encode_action()?;
    let msg = crate::crypto::signing_message(chain_id, action_type, seq, &payload);
    let sig = signing_key.sign(&msg);

    let pubkey = signing_key.verifying_key().to_bytes();
    let signature = sig.to_bytes();

    let envelope = WireTxEnvelope {
        version: ENVELOPE_VERSION,
        action_type,
        seq,
        payload,
        pubkey,
        signature,
    };
    rmp_serde::to_vec(&envelope).map_err(|e| ExecError::InternalError(e.to_string()))
}

/// Test-only convenience: sign with the `UNBOUND_CHAIN_ID`. Production
/// code MUST use `sign_and_encode_with_chain` with a real chain_id,
/// otherwise the signature is trivially replayable on any
/// zero-chain_id deployment. Kept public because `exchange-core`
/// integration tests are spread across multiple modules.
pub fn sign_and_encode(
    action: &Action,
    seq: u64,
    signing_key: &ed25519_dalek::SigningKey,
) -> Result<Vec<u8>, ExecError> {
    sign_and_encode_with_chain(&crate::crypto::UNBOUND_CHAIN_ID, action, seq, signing_key)
}

/// Sign a raw payload (bytes + action_type) and encode it as a wire envelope.
/// Used by PyO3 / WASM bindings that hold pre-encoded payload bytes.
pub fn sign_and_encode_payload(
    chain_id: &[u8; 32],
    action_type: u8,
    payload: &[u8],
    seq: u64,
    signing_key: &ed25519_dalek::SigningKey,
) -> Result<Vec<u8>, ExecError> {
    use ed25519_dalek::Signer;

    let msg = crate::crypto::signing_message(chain_id, action_type, seq, payload);
    let sig = signing_key.sign(&msg);
    let pubkey = signing_key.verifying_key().to_bytes();
    let signature = sig.to_bytes();

    let envelope = WireTxEnvelope {
        version: ENVELOPE_VERSION,
        action_type,
        seq,
        payload: WireBlob(payload.to_vec()),
        pubkey,
        signature,
    };
    rmp_serde::to_vec(&envelope).map_err(|e| ExecError::InternalError(e.to_string()))
}

/// Encode pre-signed components into a wire envelope (raw payload version).
/// Used by PyO3 / WASM bindings.
pub fn encode_signed_tx_raw(
    action_type: u8,
    payload: &[u8],
    seq: u64,
    pubkey: &[u8; 32],
    signature: &[u8; 64],
) -> Result<Vec<u8>, ExecError> {
    let envelope = WireTxEnvelope {
        version: ENVELOPE_VERSION,
        action_type,
        seq,
        payload: WireBlob(payload.to_vec()),
        pubkey: *pubkey,
        signature: *signature,
    };
    rmp_serde::to_vec(&envelope).map_err(|e| ExecError::InternalError(e.to_string()))
}

/// Decoded wire envelope components (raw, no Action enum).
pub struct DecodedTxRaw {
    pub version: u8,
    pub action_type: u8,
    pub seq: u64,
    pub payload: Vec<u8>,
    pub pubkey: [u8; 32],
    pub signature: [u8; 64],
}

/// Decode raw tx bytes into raw components without parsing the action payload.
/// Used by PyO3 / WASM bindings where the payload is opaque.
pub fn decode_tx_raw(bytes: &[u8]) -> Result<DecodedTxRaw, ExecError> {
    if bytes.is_empty() {
        return Err(ExecError::DecodeError("empty tx".to_string()));
    }
    let envelope: WireTxEnvelope =
        rmp_serde::from_slice(bytes).map_err(|e| ExecError::DecodeError(e.to_string()))?;
    if !SUPPORTED_ENVELOPE_VERSIONS.contains(&envelope.version) {
        return Err(ExecError::DecodeError(format!(
            "unsupported envelope version: {} (supported: {:?})",
            envelope.version, SUPPORTED_ENVELOPE_VERSIONS
        )));
    }
    Ok(DecodedTxRaw {
        version: envelope.version,
        action_type: envelope.action_type,
        seq: envelope.seq,
        payload: envelope.payload.0,
        pubkey: envelope.pubkey,
        signature: envelope.signature,
    })
}

/// Extract the action_type byte from a wire tx without full decoding.
pub fn peek_action_type(bytes: &[u8]) -> Option<u8> {
    rmp_serde::from_slice::<WireTxEnvelope>(bytes)
        .ok()
        .map(|env| env.action_type)
}

/// Extract the seq number from a wire tx without deserializing the payload action.
/// The payload bytes are read but not interpreted.
pub fn peek_seq(bytes: &[u8]) -> Option<u64> {
    let envelope: WireTxEnvelope = rmp_serde::from_slice(bytes).ok()?;
    Some(envelope.seq)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic, clippy::expect_used)]
mod tests {
    use super::*;
    use crate::types::{
        AmendOrder, ApproveAgent, CancelOrder, CancelReplaceOrder, ConfirmDeposit,
        ConfirmWithdrawal, CreateMarket, Deposit, FailWithdrawal, MarketOrder, Milliseconds,
        OracleUpdate, OracleUpdateComposite, PlaceOrder, RevokeAgent, Side, TimeInForce,
        UpdateMarketFees, Withdraw, WithdrawRequest,
    };
    use crate::wire::{Address, Pubkey};

    fn test_key() -> ed25519_dalek::SigningKey {
        ed25519_dalek::SigningKey::from_bytes(&[0x42; 32])
    }

    fn encode_tx(action: &Action, seq: u64) -> Result<Vec<u8>, ExecError> {
        sign_and_encode(action, seq, &test_key())
    }

    fn assert_round_trip(action: &Action, seq: u64) {
        let encoded = encode_tx(action, seq).unwrap();
        let dt = decode_tx(&encoded).unwrap();
        assert_eq!(dt.seq, seq);
        assert_eq!(format!("{:?}", action), format!("{:?}", dt.action),);
    }

    #[test]
    fn test_golden_vectors() {
        const PLACE_HEX: &str = include_str!("../../spec/golden-vectors/place_order.hex");
        const CANCEL_HEX: &str = include_str!("../../spec/golden-vectors/cancel_order.hex");
        const ORACLE_HEX: &str = include_str!("../../spec/golden-vectors/oracle_update.hex");

        let cases: Vec<(Action, u64, &str, u8)> = vec![
            (
                Action::PlaceOrder(PlaceOrder {
                    market: 1,
                    owner: [0x01; 20].into(),
                    side: Side::Buy,
                    price: 100,
                    quantity: 10,
                    client_order_id: None,
                    post_only: false,
                    reduce_only: false,
                    time_in_force: TimeInForce::Gtc,
                }),
                1,
                PLACE_HEX.trim(),
                PlaceOrder::ACTION_TYPE,
            ),
            (
                Action::CancelOrder(CancelOrder {
                    order_id: 42,
                    owner: [0x02; 20].into(),
                }),
                2,
                CANCEL_HEX.trim(),
                CancelOrder::ACTION_TYPE,
            ),
            (
                Action::OracleUpdate(OracleUpdate {
                    market: 1,
                    price: 5000,
                    signer: [0x03; 20].into(),
                    publish_time_ms: 0,
                }),
                3,
                ORACLE_HEX.trim(),
                OracleUpdate::ACTION_TYPE,
            ),
        ];

        for (action, seq, expected_hex, action_type) in cases {
            let encoded_a = encode_tx(&action, seq).unwrap();
            let encoded_b = encode_tx(&action, seq).unwrap();
            assert_eq!(encoded_a, encoded_b, "encoding must be deterministic");
            assert_eq!(
                hex::encode(&encoded_a),
                expected_hex,
                "golden vector mismatch"
            );

            let dt = decode_tx(&encoded_a).unwrap();
            assert_eq!(dt.seq, seq);

            assert_eq!(peek_action_type(&encoded_a), Some(action_type));
        }
    }

    #[test]
    fn test_round_trip_amend_order() {
        let action = Action::AmendOrder(AmendOrder {
            owner: [0xCD; 20].into(),
            order_id: 42,
            new_price: Some(12346),
            new_quantity: Some(8),
        });

        let encoded = encode_tx(&action, 202).unwrap();
        assert_eq!(peek_action_type(&encoded), Some(AmendOrder::ACTION_TYPE));
        let DecodedTx {
            action: decoded,
            seq,
            ..
        } = decode_tx(&encoded).unwrap();

        assert_eq!(seq, 202);
        match decoded {
            Action::AmendOrder(cmd) => {
                assert_eq!(cmd.owner, Address([0xCD; 20]));
                assert_eq!(cmd.order_id, 42);
                assert_eq!(cmd.new_price, Some(12346));
                assert_eq!(cmd.new_quantity, Some(8));
            }
            _ => panic!("expected AmendOrder"),
        }
    }

    #[test]
    fn test_reject_unsupported_envelope_versions() {
        // Strict mode: only versions listed in SUPPORTED_ENVELOPE_VERSIONS
        // decode. v1 (legacy unsigned) and any future-but-not-yet-shipped
        // v3 must both bounce out of decode_tx.
        for bad_version in [0u8, 1, 3, 255] {
            let bad_envelope = WireTxEnvelope {
                version: bad_version,
                action_type: PlaceOrder::ACTION_TYPE,
                seq: 0,
                payload: WireBlob::from_test_payload(
                    rmp_serde::to_vec(&PlaceOrder {
                        market: 1,
                        owner: [0x00; 20].into(),
                        side: Side::Buy,
                        price: 1,
                        quantity: 1,
                        client_order_id: None,
                        post_only: false,
                        reduce_only: false,
                        time_in_force: TimeInForce::Gtc,
                    })
                    .unwrap(),
                ),
                pubkey: [0u8; 32],
                signature: [0u8; 64],
            };
            let encoded = rmp_serde::to_vec(&bad_envelope).unwrap();
            let result = decode_tx(&encoded);
            assert!(
                result.is_err(),
                "version {} should be rejected",
                bad_version
            );
        }
    }

    // -----------------------------------------------------------------------
    // Stress tests
    // -----------------------------------------------------------------------

    /// Helper: build one instance of every Action variant with realistic values.
    fn all_action_variants() -> Vec<Action> {
        vec![
            Action::PlaceOrder(PlaceOrder {
                market: 1,
                owner: [0xAA; 20].into(),
                side: Side::Buy,
                price: 50_000,
                quantity: 100,
                client_order_id: Some(7),
                post_only: false,
                reduce_only: false,
                time_in_force: TimeInForce::Gtc,
            }),
            Action::CancelOrder(CancelOrder {
                order_id: 42,
                owner: [0xBB; 20].into(),
            }),
            Action::CancelReplaceOrder(CancelReplaceOrder {
                owner: [0xBC; 20].into(),
                cancel_order_id: Some(42),
                cancel_client_order_id: None,
                market: 1,
                side: Side::Sell,
                price: 50_100,
                quantity: 80,
                client_order_id: Some(8),
                post_only: true,
                reduce_only: false,
                time_in_force: TimeInForce::Ioc,
            }),
            Action::AmendOrder(AmendOrder {
                owner: [0xBD; 20].into(),
                order_id: 42,
                new_price: Some(50_200),
                new_quantity: Some(75),
            }),
            Action::OracleUpdate(OracleUpdate {
                market: 2,
                price: 60_000,
                signer: [0xCC; 20].into(),
                publish_time_ms: 0,
            }),
            Action::MarketOrder(MarketOrder {
                market: 3,
                owner: [0xDD; 20].into(),
                side: Side::Sell,
                quantity: 250,
                client_order_id: None,
            }),
            Action::Deposit(Deposit {
                owner: [0x11; 20].into(),
                amount: 1_000_000,
                signer: [0xEE; 20].into(),
            }),
            Action::Withdraw(Withdraw {
                owner: [0x22; 20].into(),
                amount: 500_000,
                signer: [0xEE; 20].into(),
            }),
            Action::CreateMarket(CreateMarket {
                market: 10,
                im_bps: 1000,
                mm_bps: 500,
                taker_fee_bps: 0,
                maker_fee_bps: 0,
                signer: [0xEE; 20].into(),
                funding_interval_ms: 0,
                max_funding_rate_bps: 0,
                pool_id: 0,
                sz_decimals: 0,
                ticker: String::new(),
                max_open_interest: 0,
            }),
            Action::WithdrawRequest(WithdrawRequest {
                owner: [0x33; 20].into(),
                amount: 250_000,
                solana_destination: [0x44; 32].into(),
            }),
            Action::ConfirmDeposit(ConfirmDeposit {
                owner: [0x55; 20].into(),
                amount: 100_000,
                solana_tx_sig: vec![0xAB; 64].into(),
                signer: [0x66; 20].into(),
            }),
            Action::ConfirmWithdrawal(ConfirmWithdrawal {
                withdrawal_id: 99,
                solana_tx_sig: vec![0xCD; 64].into(),
                signer: [0x77; 20].into(),
            }),
            Action::FailWithdrawal(FailWithdrawal {
                withdrawal_id: 100,
                reason: "destination account closed".to_string(),
                signer: [0x88; 20].into(),
            }),
            Action::ApproveAgent(ApproveAgent {
                owner: [0x99; 20].into(),
                agent_pubkey: [0xAA; 32].into(),
            }),
            Action::RevokeAgent(RevokeAgent {
                owner: [0xBB; 20].into(),
                agent_pubkey: [0xCC; 32].into(),
            }),
        ]
    }

    #[test]
    fn test_all_action_types_round_trip() {
        for (i, action) in all_action_variants().into_iter().enumerate() {
            assert_round_trip(&action, (i as u64) + 1);
        }
    }

    #[derive(Serialize)]
    struct LegacyCreateMarket {
        market: u32,
        im_bps: u32,
        mm_bps: u32,
        taker_fee_bps: u32,
        maker_fee_bps: u32,
        signer: [u8; 20],
        funding_interval_ms: Milliseconds,
        max_funding_rate_bps: u32,
    }

    #[test]
    fn create_market_legacy_8field_payload_now_rejected() {
        // `sz_decimals` and `ticker` are MANDATORY on the engine (no
        // `serde(default)`), and positionally they sit after `pool_id`, so a
        // legacy 8-field CreateMarket payload (pre-sz_decimals) can no longer
        // decode — it is rejected at decode exactly as the engine rejects it.
        // This documents the backward-incompatible tightening that brought the
        // SDK back into parity with the engine struct.
        let legacy = LegacyCreateMarket {
            market: 10,
            im_bps: 1000,
            mm_bps: 500,
            taker_fee_bps: 0,
            maker_fee_bps: 0,
            signer: [0xEE; 20],
            funding_interval_ms: 0,
            max_funding_rate_bps: 0,
        };
        let envelope = WireTxEnvelope {
            version: 2,
            action_type: CreateMarket::ACTION_TYPE,
            seq: 42,
            payload: WireBlob::from_test_payload(rmp_serde::to_vec(&legacy).unwrap()),
            pubkey: [0u8; 32],
            signature: [0u8; 64],
        };
        let encoded = rmp_serde::to_vec(&envelope).unwrap();
        assert!(
            decode_tx(&encoded).is_err(),
            "legacy 8-field CreateMarket must be rejected now that sz_decimals/ticker are mandatory"
        );
    }

    #[derive(Debug, Serialize, Deserialize)]
    struct PreOpenInterestCreateMarket {
        market: u32,
        im_bps: u32,
        mm_bps: u32,
        taker_fee_bps: u32,
        maker_fee_bps: u32,
        signer: Address,
        funding_interval_ms: Milliseconds,
        max_funding_rate_bps: u32,
        pool_id: u8,
        sz_decimals: u8,
        ticker: String,
    }

    #[derive(Debug, Default, Serialize, Deserialize)]
    struct PreRiskTailUpdateMarketFees {
        market: u32,
        signer: Address,
        taker_fee_bps: Option<u32>,
        maker_fee_bps: Option<u32>,
        max_funding_rate_bps: Option<u32>,
        funding_interval_ms: Option<Milliseconds>,
        max_position_size: Option<u64>,
        default_ttl_ms: Option<Milliseconds>,
        net_delta_margin: Option<bool>,
        tick_size: Option<u64>,
        lot_size: Option<u64>,
        primary_oracle_signer: Option<Address>,
        oracle_staleness_ms: Option<Milliseconds>,
        mark_source_mode: Option<crate::types::MarkSourceMode>,
        max_mark_spread_bps: Option<u32>,
        cex_composite_staleness_ms: Option<Milliseconds>,
        partial_liquidation_enabled: Option<bool>,
        fee_tiers: Option<Vec<crate::types::FeeTier>>,
    }

    impl PreRiskTailUpdateMarketFees {
        fn new(market: u32, signer: Address) -> Self {
            Self {
                market,
                signer,
                ..Self::default()
            }
        }
    }

    /// Released engine-v1 UpdateMarketFees shape. The SDK had lagged the
    /// engine's IM/MM tails, so this separate 20-field stand-in is required to
    /// prove compatibility against the real prior wire contract rather than
    /// only against the SDK's stale 18-field shape above.
    #[derive(Debug, Default, Serialize, Deserialize)]
    struct FrozenV1UpdateMarketFees {
        market: u32,
        signer: Address,
        taker_fee_bps: Option<u32>,
        maker_fee_bps: Option<u32>,
        max_funding_rate_bps: Option<u32>,
        funding_interval_ms: Option<Milliseconds>,
        max_position_size: Option<u64>,
        default_ttl_ms: Option<Milliseconds>,
        net_delta_margin: Option<bool>,
        tick_size: Option<u64>,
        lot_size: Option<u64>,
        primary_oracle_signer: Option<Address>,
        oracle_staleness_ms: Option<Milliseconds>,
        mark_source_mode: Option<crate::types::MarkSourceMode>,
        max_mark_spread_bps: Option<u32>,
        cex_composite_staleness_ms: Option<Milliseconds>,
        partial_liquidation_enabled: Option<bool>,
        fee_tiers: Option<Vec<crate::types::FeeTier>>,
        im_bps: Option<u32>,
        mm_bps: Option<u32>,
    }

    impl FrozenV1UpdateMarketFees {
        fn new(market: u32, signer: Address) -> Self {
            Self {
                market,
                signer,
                ..Self::default()
            }
        }
    }

    #[test]
    fn create_market_open_interest_tail_is_optional_and_round_trips() {
        let legacy = PreOpenInterestCreateMarket {
            market: 42,
            im_bps: 1000,
            mm_bps: 500,
            taker_fee_bps: 5,
            maker_fee_bps: 2,
            signer: [0xEE; 20].into(),
            funding_interval_ms: 60_000,
            max_funding_rate_bps: 100,
            pool_id: 9,
            sz_decimals: 5,
            ticker: "BTC".to_string(),
        };
        let uncapped = CreateMarket {
            market: 42,
            im_bps: 1000,
            mm_bps: 500,
            taker_fee_bps: 5,
            maker_fee_bps: 2,
            signer: [0xEE; 20].into(),
            funding_interval_ms: 60_000,
            max_funding_rate_bps: 100,
            pool_id: 9,
            sz_decimals: 5,
            ticker: "BTC".to_string(),
            max_open_interest: 0,
        };

        let legacy_bytes = rmp_serde::to_vec(&legacy).unwrap();
        assert_eq!(rmp_serde::to_vec(&uncapped).unwrap(), legacy_bytes);
        let legacy_decoded: CreateMarket = rmp_serde::from_slice(&legacy_bytes).unwrap();
        assert_eq!(legacy_decoded.max_open_interest, 0);

        let capped = CreateMarket {
            max_open_interest: 1_000_000,
            ..uncapped
        };
        let capped_bytes = rmp_serde::to_vec(&capped).unwrap();
        let fields: Vec<serde_json::Value> = rmp_serde::from_slice(&capped_bytes).unwrap();
        assert_eq!(fields.len(), 12);
        assert_eq!(fields[11], serde_json::json!(1_000_000));
        let capped_decoded: CreateMarket = rmp_serde::from_slice(&capped_bytes).unwrap();
        assert_eq!(capped_decoded.max_open_interest, 1_000_000);
        let error =
            rmp_serde::from_slice::<PreOpenInterestCreateMarket>(&capped_bytes).unwrap_err();
        assert!(
            error.to_string().contains("length") || error.to_string().contains("LengthMismatch"),
            "unexpected frozen v1 CreateMarket decoder error: {error}"
        );
    }

    #[test]
    fn update_market_fees_uses_margin_slots_before_open_interest_cap() {
        let update = UpdateMarketFees {
            im_bps: Some(3334),
            mm_bps: Some(1667),
            max_open_interest: Some(500_000),
            ..UpdateMarketFees::new(42, [0xEE; 20].into())
        };

        let payload = rmp_serde::to_vec(&update).unwrap();
        let fields: Vec<serde_json::Value> = rmp_serde::from_slice(&payload).unwrap();
        assert_eq!(fields.len(), 21);
        assert_eq!(fields[18], serde_json::json!(3334));
        assert_eq!(fields[19], serde_json::json!(1667));
        assert_eq!(fields[20], serde_json::json!(500_000));

        let decoded: UpdateMarketFees = rmp_serde::from_slice(&payload).unwrap();
        assert_eq!(decoded.im_bps, Some(3334));
        assert_eq!(decoded.mm_bps, Some(1667));
        assert_eq!(decoded.max_open_interest, Some(500_000));

        // The SDK's stale pre-risk-tail 18-field form remains accepted.
        let stale_sdk = PreRiskTailUpdateMarketFees::new(42, [0xEE; 20].into());
        let stale_sdk_payload = rmp_serde::to_vec(&stale_sdk).unwrap();
        let stale_sdk_decoded: UpdateMarketFees =
            rmp_serde::from_slice(&stale_sdk_payload).unwrap();
        assert_eq!(stale_sdk_decoded.im_bps, None);
        assert_eq!(stale_sdk_decoded.mm_bps, None);
        assert_eq!(stale_sdk_decoded.max_open_interest, None);

        // More importantly, model the actual released engine-v1 decoder and
        // payload: it already had IM/MM at slots 18/19 and only lacks max OI.
        let frozen_v1 = FrozenV1UpdateMarketFees {
            im_bps: Some(3334),
            mm_bps: Some(1667),
            ..FrozenV1UpdateMarketFees::new(42, [0xEE; 20].into())
        };
        let frozen_v1_payload = rmp_serde::to_vec(&frozen_v1).unwrap();
        let frozen_v1_fields: Vec<serde_json::Value> =
            rmp_serde::from_slice(&frozen_v1_payload).unwrap();
        assert_eq!(frozen_v1_fields.len(), 20);
        let frozen_v1_decoded: UpdateMarketFees =
            rmp_serde::from_slice(&frozen_v1_payload).unwrap();
        assert_eq!(frozen_v1_decoded.im_bps, Some(3334));
        assert_eq!(frozen_v1_decoded.mm_bps, Some(1667));
        assert_eq!(frozen_v1_decoded.max_open_interest, None);

        let error = rmp_serde::from_slice::<FrozenV1UpdateMarketFees>(&payload).unwrap_err();
        assert!(
            error.to_string().contains("length") || error.to_string().contains("LengthMismatch"),
            "unexpected frozen v1 UpdateMarketFees decoder error: {error}"
        );
    }

    fn max_value_actions() -> Vec<Action> {
        vec![
            Action::PlaceOrder(PlaceOrder {
                market: u32::MAX,
                owner: [0xFF; 20].into(),
                side: Side::Sell,
                price: u64::MAX,
                quantity: u64::MAX,
                client_order_id: Some(u64::MAX),
                post_only: false,
                reduce_only: false,
                time_in_force: TimeInForce::Gtc,
            }),
            Action::CancelOrder(CancelOrder {
                order_id: u64::MAX,
                owner: [0xFF; 20].into(),
            }),
            Action::OracleUpdate(OracleUpdate {
                market: u32::MAX,
                price: u64::MAX,
                signer: [0xFF; 20].into(),
                publish_time_ms: 0,
            }),
            Action::MarketOrder(MarketOrder {
                market: u32::MAX,
                owner: [0xFF; 20].into(),
                side: Side::Buy,
                quantity: u64::MAX,
                client_order_id: Some(u64::MAX),
            }),
            Action::Deposit(Deposit {
                owner: [0xFF; 20].into(),
                amount: u64::MAX,
                signer: [0xEE; 20].into(),
            }),
            Action::Withdraw(Withdraw {
                owner: [0xFF; 20].into(),
                amount: u64::MAX,
                signer: [0xEE; 20].into(),
            }),
            Action::CreateMarket(CreateMarket {
                market: u32::MAX,
                im_bps: u32::MAX,
                mm_bps: u32::MAX,
                taker_fee_bps: u32::MAX,
                maker_fee_bps: u32::MAX,
                signer: [0xFF; 20].into(),
                funding_interval_ms: u64::MAX,
                max_funding_rate_bps: u32::MAX,
                pool_id: 0,
                sz_decimals: 0,
                ticker: String::new(),
                max_open_interest: u64::MAX,
            }),
            Action::WithdrawRequest(WithdrawRequest {
                owner: [0xFF; 20].into(),
                amount: u64::MAX,
                solana_destination: [0xFF; 32].into(),
            }),
            Action::ConfirmDeposit(ConfirmDeposit {
                owner: [0xFF; 20].into(),
                amount: u64::MAX,
                solana_tx_sig: vec![0xFF; 1024].into(),
                signer: [0xFF; 20].into(),
            }),
            Action::ConfirmWithdrawal(ConfirmWithdrawal {
                withdrawal_id: u64::MAX,
                solana_tx_sig: vec![0xFF; 1024].into(),
                signer: [0xFF; 20].into(),
            }),
            Action::FailWithdrawal(FailWithdrawal {
                withdrawal_id: u64::MAX,
                reason: "x".repeat(1024),
                signer: [0xFF; 20].into(),
            }),
        ]
    }

    fn min_value_actions() -> Vec<Action> {
        vec![
            Action::PlaceOrder(PlaceOrder {
                market: 0,
                owner: [0u8; 20].into(),
                side: Side::Buy,
                price: 0,
                quantity: 0,
                client_order_id: None,
                post_only: false,
                reduce_only: false,
                time_in_force: TimeInForce::Gtc,
            }),
            Action::CancelOrder(CancelOrder {
                order_id: 0,
                owner: [0u8; 20].into(),
            }),
            Action::OracleUpdate(OracleUpdate {
                market: 0,
                price: 0,
                signer: [0u8; 20].into(),
                publish_time_ms: 0,
            }),
            Action::MarketOrder(MarketOrder {
                market: 0,
                owner: [0u8; 20].into(),
                side: Side::Buy,
                quantity: 0,
                client_order_id: None,
            }),
            Action::Deposit(Deposit {
                owner: [0u8; 20].into(),
                amount: 0,
                signer: [0xEE; 20].into(),
            }),
            Action::Withdraw(Withdraw {
                owner: [0u8; 20].into(),
                amount: 0,
                signer: [0xEE; 20].into(),
            }),
            Action::CreateMarket(CreateMarket {
                market: 0,
                im_bps: 0,
                mm_bps: 0,
                taker_fee_bps: 0,
                maker_fee_bps: 0,
                signer: [0u8; 20].into(),
                funding_interval_ms: 0,
                max_funding_rate_bps: 0,
                pool_id: 0,
                sz_decimals: 0,
                ticker: String::new(),
                max_open_interest: 0,
            }),
            Action::WithdrawRequest(WithdrawRequest {
                owner: [0u8; 20].into(),
                amount: 0,
                solana_destination: [0u8; 32].into(),
            }),
            Action::ConfirmDeposit(ConfirmDeposit {
                owner: [0u8; 20].into(),
                amount: 0,
                solana_tx_sig: vec![].into(),
                signer: [0u8; 20].into(),
            }),
            Action::ConfirmWithdrawal(ConfirmWithdrawal {
                withdrawal_id: 0,
                solana_tx_sig: vec![].into(),
                signer: [0u8; 20].into(),
            }),
            Action::FailWithdrawal(FailWithdrawal {
                withdrawal_id: 0,
                reason: String::new(),
                signer: [0u8; 20].into(),
            }),
        ]
    }

    #[test]
    fn test_codec_max_values() {
        for action in max_value_actions() {
            assert_round_trip(&action, u64::MAX);
        }
    }

    #[test]
    fn test_codec_empty_and_minimal() {
        for action in min_value_actions() {
            assert_round_trip(&action, 0);
        }
    }

    #[test]
    fn stress_codec_round_trip_all_types_1000() {
        for i in 0u64..1000 {
            let market = (i as u32) % 100;
            let mut owner = [0u8; 20];
            owner[0..8].copy_from_slice(&i.to_le_bytes());
            let mut dest = [0u8; 32];
            dest[0..8].copy_from_slice(&i.to_le_bytes());
            let owner: Address = owner.into();
            let dest: Pubkey = dest.into();

            let actions: Vec<Action> = vec![
                Action::PlaceOrder(PlaceOrder {
                    market,
                    owner,
                    side: if i % 2 == 0 { Side::Buy } else { Side::Sell },
                    price: i * 100,
                    quantity: i + 1,
                    client_order_id: if i % 3 == 0 { Some(i) } else { None },
                    post_only: false,
                    reduce_only: false,
                    time_in_force: TimeInForce::Gtc,
                }),
                Action::CancelOrder(CancelOrder { order_id: i, owner }),
                Action::OracleUpdate(OracleUpdate {
                    market,
                    price: i * 50,
                    signer: owner,
                    publish_time_ms: 0,
                }),
                Action::MarketOrder(MarketOrder {
                    market,
                    owner,
                    side: if i % 2 == 0 { Side::Sell } else { Side::Buy },
                    quantity: i + 10,
                    client_order_id: if i % 5 == 0 { Some(i * 7) } else { None },
                }),
                Action::Deposit(Deposit {
                    owner,
                    amount: i * 1000,
                    signer: [0xEE; 20].into(),
                }),
                Action::Withdraw(Withdraw {
                    owner,
                    amount: i * 500,
                    signer: [0xEE; 20].into(),
                }),
                Action::CreateMarket(CreateMarket {
                    market,
                    im_bps: (i as u32) % 5000,
                    mm_bps: (i as u32) % 2500,
                    taker_fee_bps: 0,
                    maker_fee_bps: 0,
                    signer: owner,
                    funding_interval_ms: 0,
                    max_funding_rate_bps: 0,
                    pool_id: 0,
                    sz_decimals: 0,
                    ticker: String::new(),
                    max_open_interest: i + 1,
                }),
                Action::WithdrawRequest(WithdrawRequest {
                    owner,
                    amount: i * 200,
                    solana_destination: dest,
                }),
                Action::ConfirmDeposit(ConfirmDeposit {
                    owner,
                    amount: i * 300,
                    solana_tx_sig: i.to_le_bytes().to_vec().into(),
                    signer: owner,
                }),
                Action::ConfirmWithdrawal(ConfirmWithdrawal {
                    withdrawal_id: i,
                    solana_tx_sig: i.to_le_bytes().to_vec().into(),
                    signer: owner,
                }),
                Action::FailWithdrawal(FailWithdrawal {
                    withdrawal_id: i,
                    reason: format!("fail_{i}"),
                    signer: owner,
                }),
            ];

            for (j, action) in actions.into_iter().enumerate() {
                let seq = i * 11 + (j as u64);
                let encoded = encode_tx(&action, seq).unwrap();
                let dt = decode_tx(&encoded).unwrap();
                assert_eq!(dt.seq, seq);
                assert_eq!(
                    format!("{:?}", action),
                    format!("{:?}", dt.action),
                    "stress mismatch at i={i}, variant={j}"
                );
            }
        }
    }

    #[test]
    fn test_peek_action_type() {
        for action in all_action_variants() {
            let encoded = encode_tx(&action, 1).unwrap();
            let peeked = peek_action_type(&encoded);
            let expected = action.encode_action().unwrap().action_type;
            assert_eq!(peeked, Some(expected), "peek mismatch for {action:?}");
        }
    }

    #[test]
    fn test_decode_truncated_bytes() {
        let action = Action::PlaceOrder(PlaceOrder {
            market: 1,
            owner: [0xAA; 20].into(),
            side: Side::Buy,
            price: 50_000,
            quantity: 100,
            client_order_id: Some(42),
            post_only: false,
            reduce_only: false,
            time_in_force: TimeInForce::Gtc,
        });
        let encoded = encode_tx(&action, 99).unwrap();

        // Try decoding every truncated prefix (skip len 0 since empty is
        // trivially an error).
        for len in 1..encoded.len() {
            let truncated = &encoded[..len];
            let result = decode_tx(truncated);
            assert!(
                result.is_err(),
                "expected error for truncated bytes (len={len}/{})",
                encoded.len()
            );
        }
    }

    #[test]
    fn test_decode_random_garbage() {
        // Simple deterministic PRNG (xorshift64) to avoid external deps.
        let mut state: u64 = 0xDEAD_BEEF_CAFE_BABE;
        let mut next = || -> u64 {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            state
        };

        for _ in 0..100 {
            let len = (next() % 256) as usize + 1;
            let garbage: Vec<u8> = (0..len).map(|_| (next() & 0xFF) as u8).collect();
            // Must not panic — errors are fine.
            let _ = decode_tx(&garbage);
        }
    }

    // -----------------------------------------------------------------------
    // V2 (signed) envelope tests
    // -----------------------------------------------------------------------

    fn test_signing_key() -> ed25519_dalek::SigningKey {
        ed25519_dalek::SigningKey::from_bytes(&[0x42; 32])
    }

    #[test]
    fn test_v2_round_trip_all_action_types() {
        let key = test_signing_key();
        let actions: Vec<Action> = vec![
            Action::PlaceOrder(PlaceOrder {
                market: 1,
                owner: [0; 20].into(),
                side: Side::Buy,
                price: 1,
                quantity: 1,
                client_order_id: None,
                post_only: false,
                reduce_only: false,
                time_in_force: TimeInForce::Gtc,
            }),
            Action::CancelOrder(CancelOrder {
                order_id: 1,
                owner: [0; 20].into(),
            }),
            Action::OracleUpdate(OracleUpdate {
                market: 1,
                price: 100,
                signer: [0; 20].into(),
                publish_time_ms: 0,
            }),
            Action::MarketOrder(MarketOrder {
                market: 1,
                owner: [0; 20].into(),
                side: Side::Sell,
                quantity: 1,
                client_order_id: None,
            }),
            Action::Deposit(Deposit {
                owner: [0; 20].into(),
                amount: 1,
                signer: [0xEE; 20].into(),
            }),
            Action::Withdraw(Withdraw {
                owner: [0; 20].into(),
                amount: 1,
                signer: [0xEE; 20].into(),
            }),
            Action::CreateMarket(CreateMarket {
                market: 1,
                im_bps: 1000,
                mm_bps: 500,
                taker_fee_bps: 0,
                maker_fee_bps: 0,
                signer: [0xEE; 20].into(),
                funding_interval_ms: 0,
                max_funding_rate_bps: 0,
                pool_id: 0,
                sz_decimals: 0,
                ticker: String::new(),
                max_open_interest: 0,
            }),
            Action::WithdrawRequest(WithdrawRequest {
                owner: [0; 20].into(),
                amount: 1,
                solana_destination: [0; 32].into(),
            }),
            Action::ConfirmDeposit(ConfirmDeposit {
                owner: [0; 20].into(),
                amount: 1,
                solana_tx_sig: vec![0; 64].into(),
                signer: [0; 20].into(),
            }),
            Action::ConfirmWithdrawal(ConfirmWithdrawal {
                withdrawal_id: 1,
                solana_tx_sig: vec![0; 64].into(),
                signer: [0; 20].into(),
            }),
            Action::FailWithdrawal(FailWithdrawal {
                withdrawal_id: 1,
                reason: "test".into(),
                signer: [0; 20].into(),
            }),
            Action::ApproveAgent(ApproveAgent {
                owner: [0xAA; 20].into(),
                agent_pubkey: [0xBB; 32].into(),
            }),
            Action::RevokeAgent(RevokeAgent {
                owner: [0xAA; 20].into(),
                agent_pubkey: [0xBB; 32].into(),
            }),
        ];

        for action in actions {
            let encoded = sign_and_encode(&action, 1, &key).unwrap();
            let decoded = decode_tx(&encoded).unwrap();
            assert_eq!(decoded.seq, 1);
        }
    }

    #[test]
    fn test_v2_signature_verifies() {
        let key = test_signing_key();
        let action = Action::Deposit(Deposit {
            owner: [0xCC; 20].into(),
            amount: 5000,
            signer: [0xEE; 20].into(),
        });
        let encoded = sign_and_encode(&action, 99, &key).unwrap();
        let decoded = decode_tx(&encoded).unwrap();

        let auth = decoded.auth;
        // Signature should verify against the signing message
        let result = crate::crypto::verify_signature(
            &crate::crypto::UNBOUND_CHAIN_ID,
            &auth.pubkey,
            &auth.signature,
            auth.action_type,
            decoded.seq,
            &auth.payload,
        );
        assert!(result.is_ok(), "signature should verify");
    }

    #[test]
    fn test_v2_wrong_key_fails_verification() {
        let key = test_signing_key();
        let wrong_key = ed25519_dalek::SigningKey::from_bytes(&[0x99; 32]);
        let action = Action::Deposit(Deposit {
            owner: [0xCC; 20].into(),
            amount: 5000,
            signer: [0xEE; 20].into(),
        });
        let encoded = sign_and_encode(&action, 99, &key).unwrap();
        let decoded = decode_tx(&encoded).unwrap();

        let auth = decoded.auth;
        // Verify with the wrong key's pubkey should fail
        let wrong_pubkey = wrong_key.verifying_key().to_bytes();
        let result = crate::crypto::verify_signature(
            &crate::crypto::UNBOUND_CHAIN_ID,
            &wrong_pubkey,
            &auth.signature,
            auth.action_type,
            decoded.seq,
            &auth.payload,
        );
        assert!(result.is_err(), "wrong key should fail verification");
    }

    #[test]
    fn test_v2_wrong_pubkey_length_rejected() {
        // Build a valid v2 envelope, then re-encode with a wrong-length pubkey
        // using a helper struct that allows Vec<u8> for pubkey.
        #[derive(Serialize)]
        struct BadEnvelope {
            version: u8,
            action_type: u8,
            seq: u64,
            payload: Vec<u8>,
            pubkey: Vec<u8>,
            signature: Vec<u8>,
        }
        let encoded = rmp_serde::to_vec(&BadEnvelope {
            version: 2,
            action_type: PlaceOrder::ACTION_TYPE,
            seq: 1,
            payload: rmp_serde::to_vec(&PlaceOrder {
                market: 1,
                owner: [0; 20].into(),
                side: Side::Buy,
                price: 1,
                quantity: 1,
                client_order_id: None,
                post_only: false,
                reduce_only: false,
                time_in_force: TimeInForce::Gtc,
            })
            .unwrap(),
            pubkey: vec![0u8; 16], // wrong: should be 32
            signature: vec![0u8; 64],
        })
        .unwrap();
        let result = decode_tx(&encoded);
        assert!(result.is_err());
    }

    #[test]
    fn test_v2_wrong_signature_length_rejected() {
        #[derive(Serialize)]
        struct BadEnvelope {
            version: u8,
            action_type: u8,
            seq: u64,
            payload: Vec<u8>,
            pubkey: Vec<u8>,
            signature: Vec<u8>,
        }
        let encoded = rmp_serde::to_vec(&BadEnvelope {
            version: 2,
            action_type: PlaceOrder::ACTION_TYPE,
            seq: 1,
            payload: rmp_serde::to_vec(&PlaceOrder {
                market: 1,
                owner: [0; 20].into(),
                side: Side::Buy,
                price: 1,
                quantity: 1,
                client_order_id: None,
                post_only: false,
                reduce_only: false,
                time_in_force: TimeInForce::Gtc,
            })
            .unwrap(),
            pubkey: vec![0u8; 32],
            signature: vec![0u8; 32], // wrong: should be 64
        })
        .unwrap();
        let result = decode_tx(&encoded);
        assert!(result.is_err());
    }

    #[test]
    fn test_peek_action_type_v2() {
        let key = test_signing_key();
        for action in all_action_variants() {
            let encoded = sign_and_encode(&action, 1, &key).unwrap();
            let peeked = peek_action_type(&encoded);
            let expected = action.encode_action().unwrap().action_type;
            assert_eq!(peeked, Some(expected), "v2 peek mismatch for {action:?}");
        }
    }

    #[test]
    fn test_v2_encode_decode_deterministic() {
        let key = test_signing_key();
        let action = Action::CancelOrder(CancelOrder {
            order_id: 42,
            owner: [0xDD; 20].into(),
        });
        let a = sign_and_encode(&action, 1, &key).unwrap();
        let b = sign_and_encode(&action, 1, &key).unwrap();
        assert_eq!(a, b, "v2 encoding must be deterministic");
    }

    // -------------------------------------------------------------------
    // Stress tests
    // -------------------------------------------------------------------

    #[test]
    fn stress_1000_v2_sign_encode_decode_verify() {
        for i in 0u32..1000 {
            let mut seed = [0u8; 32];
            seed[0..4].copy_from_slice(&i.to_le_bytes());
            let key = ed25519_dalek::SigningKey::from_bytes(&seed);

            let action = Action::PlaceOrder(PlaceOrder {
                market: (i % 100) + 1,
                owner: crate::crypto::pubkey_to_owner(&key.verifying_key().to_bytes()).into(),
                side: if i % 2 == 0 { Side::Buy } else { Side::Sell },
                price: (i as u64 + 1) * 100,
                quantity: (i as u64 + 1) * 10,
                client_order_id: Some(i as u64),
                post_only: false,
                reduce_only: false,
                time_in_force: TimeInForce::Gtc,
            });

            let encoded = sign_and_encode(&action, i as u64, &key).unwrap();
            let decoded = decode_tx(&encoded).unwrap();

            assert_eq!(decoded.seq, i as u64, "seq mismatch at i={i}");
            let auth = &decoded.auth;
            assert_eq!(auth.pubkey, key.verifying_key().to_bytes());

            // Verify signature through crypto module
            assert!(
                crate::crypto::verify_signature(
                    &crate::crypto::UNBOUND_CHAIN_ID,
                    &auth.pubkey,
                    &auth.signature,
                    auth.action_type,
                    decoded.seq,
                    &auth.payload,
                )
                .is_ok(),
                "signature verification failed at i={i}"
            );
        }
    }

    #[test]
    fn stress_all_13_action_types_v2_round_trip() {
        // Generate a unique key per action type and do 100 iterations each
        for action_idx in 0u8..13 {
            let mut seed = [0u8; 32];
            seed[0] = action_idx;
            seed[1] = 0xAB;
            let key = ed25519_dalek::SigningKey::from_bytes(&seed);
            let owner: Address =
                crate::crypto::pubkey_to_owner(&key.verifying_key().to_bytes()).into();

            for seq in 0u64..100 {
                let action = match action_idx {
                    0 => Action::PlaceOrder(PlaceOrder {
                        market: 1,
                        owner,
                        side: Side::Buy,
                        price: seq + 1,
                        quantity: seq + 1,
                        client_order_id: None,
                        post_only: false,
                        reduce_only: false,
                        time_in_force: TimeInForce::Gtc,
                    }),
                    1 => Action::CancelOrder(CancelOrder {
                        order_id: seq,
                        owner,
                    }),
                    2 => Action::OracleUpdate(OracleUpdate {
                        market: 1,
                        price: seq + 1,
                        signer: owner,
                        publish_time_ms: 0,
                    }),
                    3 => Action::MarketOrder(MarketOrder {
                        market: 1,
                        owner,
                        side: Side::Sell,
                        quantity: seq + 1,
                        client_order_id: None,
                    }),
                    4 => Action::Deposit(Deposit {
                        owner,
                        amount: seq + 1,
                        signer: [0xEE; 20].into(),
                    }),
                    5 => Action::Withdraw(Withdraw {
                        owner,
                        amount: seq + 1,
                        signer: [0xEE; 20].into(),
                    }),
                    6 => Action::CreateMarket(CreateMarket {
                        market: seq as u32 + 1,
                        im_bps: 1000,
                        mm_bps: 500,
                        taker_fee_bps: 0,
                        maker_fee_bps: 0,
                        signer: owner,
                        funding_interval_ms: 0,
                        max_funding_rate_bps: 0,
                        pool_id: 0,
                        sz_decimals: 0,
                        ticker: String::new(),
                        max_open_interest: seq + 1,
                    }),
                    7 => Action::WithdrawRequest(WithdrawRequest {
                        owner,
                        amount: seq + 1,
                        solana_destination: [0x11; 32].into(),
                    }),
                    8 => Action::ConfirmDeposit(ConfirmDeposit {
                        owner,
                        amount: seq + 1,
                        solana_tx_sig: vec![seq as u8; 64].into(),
                        signer: owner,
                    }),
                    9 => Action::ConfirmWithdrawal(ConfirmWithdrawal {
                        withdrawal_id: seq,
                        solana_tx_sig: vec![seq as u8; 64].into(),
                        signer: owner,
                    }),
                    10 => Action::FailWithdrawal(FailWithdrawal {
                        withdrawal_id: seq,
                        reason: format!("reason-{seq}"),
                        signer: owner,
                    }),
                    11 => Action::ApproveAgent(ApproveAgent {
                        owner,
                        agent_pubkey: [seq as u8; 32].into(),
                    }),
                    12 => Action::RevokeAgent(RevokeAgent {
                        owner,
                        agent_pubkey: [seq as u8; 32].into(),
                    }),
                    _ => unreachable!(),
                };

                let encoded = sign_and_encode(&action, seq, &key).unwrap();
                let decoded = decode_tx(&encoded).unwrap();

                let auth = &decoded.auth;
                assert!(
                    crate::crypto::verify_signature(
                        &crate::crypto::UNBOUND_CHAIN_ID,
                        &auth.pubkey,
                        &auth.signature,
                        auth.action_type,
                        decoded.seq,
                        &auth.payload,
                    )
                    .is_ok(),
                    "verify failed for action_idx={action_idx} seq={seq}"
                );
            }
        }
    }

    #[test]
    fn stress_v2_tamper_detection_100_txs() {
        let key = test_signing_key();

        for i in 0u64..100 {
            let action = Action::Deposit(Deposit {
                owner: crate::crypto::pubkey_to_owner(&key.verifying_key().to_bytes()).into(),
                amount: i + 1,
                signer: [0xEE; 20].into(),
            });

            let encoded = sign_and_encode(&action, i, &key).unwrap();

            // Tamper each byte — should fail decode or verification
            for byte_idx in 0..encoded.len() {
                let mut tampered = encoded.clone();
                tampered[byte_idx] ^= 0x01;
                match decode_tx(&tampered) {
                    Ok(decoded) => {
                        let auth = &decoded.auth;
                        // Decoded but signature should fail. It's fine if a
                        // tampered action_type/seq matches by accident; the
                        // signature should almost always fail anyway.
                        let _ = crate::crypto::verify_signature(
                            &crate::crypto::UNBOUND_CHAIN_ID,
                            &auth.pubkey,
                            &auth.signature,
                            auth.action_type,
                            decoded.seq,
                            &auth.payload,
                        );
                    }
                    Err(_) => {
                        // Decode failure is expected for structural tampering
                    }
                }
            }
        }
    }

    #[test]
    fn stress_boundary_seq_values() {
        let key = test_signing_key();
        let action = Action::CancelOrder(CancelOrder {
            order_id: 1,
            owner: [0xAA; 20].into(),
        });

        for seq in [
            0,
            1,
            255,
            256,
            65535,
            65536,
            u32::MAX as u64,
            u64::MAX / 2,
            u64::MAX,
        ] {
            let encoded = sign_and_encode(&action, seq, &key).unwrap();
            let decoded = decode_tx(&encoded).unwrap();
            assert_eq!(decoded.seq, seq, "seq mismatch for {seq}");
        }
    }

    #[test]
    fn stress_v2_random_garbage_no_panic() {
        // Same PRNG as existing test but with v2-sized buffers
        let mut state: u64 = 0xCAFE_BABE_DEAD_BEEF;
        let mut next = || -> u64 {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            state
        };

        for _ in 0..1000 {
            // Generate random data of sizes likely to hit v2 parsing paths
            let len = (next() % 512) as usize + 1;
            let mut garbage: Vec<u8> = (0..len).map(|_| (next() & 0xFF) as u8).collect();

            // Sometimes give it a v2 fixarray marker to exercise that path
            if next() % 3 == 0 {
                garbage[0] = 0x96; // fixarray(6)
            }

            // Must not panic
            let _ = decode_tx(&garbage);
        }
    }

    #[test]
    fn decode_legacy_create_market_8field_now_rejected() {
        // Pre-pool_id wire shape: 8-field positional msgpack array.
        // Although `pool_id` is `serde(default)`, the trailing `sz_decimals`
        // and `ticker` are MANDATORY (no default) and positionally follow
        // `pool_id`, so an 8-field array cannot satisfy the struct and is
        // rejected at decode — matching the engine. Old SDK builds that
        // pre-date sz_decimals can no longer create markets, by design.
        //
        // Field order matches the struct definition in `types.rs`:
        //   market, im_bps, mm_bps, taker_fee_bps, maker_fee_bps,
        //   signer, funding_interval_ms, max_funding_rate_bps,
        //   [pool_id intentionally omitted]
        let payload_bytes = rmp_serde::to_vec(&(
            99u32,        // market
            500u32,       // im_bps
            250u32,       // mm_bps
            5u32,         // taker_fee_bps
            2u32,         // maker_fee_bps
            [0xAAu8; 20], // signer
            60_000u64,    // funding_interval_ms
            3000u32,      // max_funding_rate_bps
                          // intentionally NO pool_id (legacy SDK)
        ))
        .unwrap();

        // Envelope uses WireBlob for payload, which enforces msgpack
        // bin encoding at the type level. The pubkey/signature are zero
        // because this test only exercises the codec's payload-decode
        // path, not signature verification.
        let envelope = WireTxEnvelope {
            version: 2,
            action_type: CreateMarket::ACTION_TYPE,
            seq: 0,
            payload: WireBlob::from_test_payload(payload_bytes),
            pubkey: [0u8; 32],
            signature: [0u8; 64],
        };
        let encoded = rmp_serde::to_vec(&envelope).unwrap();

        assert!(
            decode_tx(&encoded).is_err(),
            "legacy 8-field CreateMarket must now be rejected: sz_decimals/ticker are mandatory"
        );
    }

    #[test]
    fn atomic_basket_order_round_trips() {
        let action = Action::AtomicBasketOrder(AtomicBasketOrder {
            owner: [0x11; 20].into(),
            legs: vec![
                AtomicBasketLeg {
                    market: 1,
                    side: Side::Buy,
                    price: 6_675_000,
                    quantity: 3,
                    client_order_id: Some(77),
                    reduce_only: false,
                },
                AtomicBasketLeg {
                    market: 2,
                    side: Side::Sell,
                    price: 250_000,
                    quantity: 5,
                    client_order_id: None,
                    reduce_only: true,
                },
            ],
            max_slippage_bps: 50,
        });
        assert_round_trip(&action, 7);
        let encoded = encode_tx(&action, 7).unwrap();
        match decode_tx(&encoded).unwrap().action {
            Action::AtomicBasketOrder(b) => {
                assert_eq!(b.owner, [0x11; 20].into());
                assert_eq!(b.legs.len(), 2);
                assert_eq!(b.legs[0].client_order_id, Some(77));
                assert!(b.legs[1].reduce_only);
                assert_eq!(b.max_slippage_bps, 50);
            }
            other => panic!("expected AtomicBasketOrder, got {other:?}"),
        }
    }

    #[test]
    fn oracle_update_composite_round_trips() {
        let action = Action::OracleUpdateComposite(OracleUpdateComposite {
            market: 1,
            price: 6_675_000,
            n_sources: 4,
            signer: [0x21; 20].into(),
            publish_time_ms: 1_700_000_000_123,
        });
        assert_round_trip(&action, 14);
        let encoded = encode_tx(&action, 14).unwrap();
        assert_eq!(
            peek_action_type(&encoded),
            Some(OracleUpdateComposite::ACTION_TYPE)
        );
        assert_eq!(OracleUpdateComposite::ACTION_TYPE, 0x14);
        match decode_tx(&encoded).unwrap().action {
            Action::OracleUpdateComposite(c) => {
                assert_eq!(c.market, 1);
                assert_eq!(c.price, 6_675_000);
                assert_eq!(c.n_sources, 4);
                assert_eq!(c.signer, [0x21; 20].into());
                assert_eq!(c.publish_time_ms, 1_700_000_000_123);
            }
            other => panic!("expected OracleUpdateComposite, got {other:?}"),
        }
    }

    #[test]
    fn oracle_update_composite_trailing_publish_time_defaults() {
        // A 4-field payload (no trailing publish_time_ms) must still decode,
        // with publish_time_ms = 0 via serde(default). Proves the new field is
        // a backward-compatible (MINOR) addition: feeder records written before
        // the replay guard existed round-trip on this code.
        let payload = rmp_serde::to_vec(&(
            7u32,       // market
            250_000u64, // price
            1u8,        // n_sources
            [0x21u8; 20], // signer
                        // publish_time_ms intentionally omitted
        ))
        .unwrap();
        let envelope = WireTxEnvelope {
            version: 2,
            action_type: OracleUpdateComposite::ACTION_TYPE,
            seq: 0,
            payload: WireBlob::from_test_payload(payload),
            pubkey: [0u8; 32],
            signature: [0u8; 64],
        };
        let encoded = rmp_serde::to_vec(&envelope).unwrap();
        match decode_tx(&encoded).unwrap().action {
            Action::OracleUpdateComposite(c) => {
                assert_eq!(c.market, 7);
                assert_eq!(c.price, 250_000);
                assert_eq!(c.n_sources, 1);
                assert_eq!(c.publish_time_ms, 0, "trailing field must default to 0");
            }
            other => panic!("expected OracleUpdateComposite, got {other:?}"),
        }
    }
}
